name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        cd cvat-sdk
        pip install -r gen/requirements.txt
        ./gen/generate.sh
        cd ..
        pip install -r ./tests/python/requirements.txt
        pip install -e ./cvat-sdk
        pip install -e ./cvat-cli
        pytest tests/python/ --cov --cov-report xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
